# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

 development:
  adapter: postgresql
  encoding: unicode
  database: ms_dev
  pool: 5
  username: cejaramillof
  password: 123456789

test:
  adapter: postgresql
  encoding: unicode
  database: ms_test
  pool: 5
  username: cejaramillof
  password: 123456789